### PR TITLE
Upgrade roundcube to 1.3.7 version

### PR DESCRIPTION
**Pull request by alnikyur**

### CODE REVIEW

**Comment by alnikyur** [comment]
@tyranron FCM
```
Upgrade Roundcube to 1.3.7 release (#5)
```

**Review by tyranron — APPROVED** [review]
@alnikyur LGTM, but you need to wait until build will succeed

**Comment by alnikyur** [comment]
@tyranron OK, i will restart builds.

**Comment by alnikyur** [comment]
@tyranron OK, i will restart builds until success.

**Pull request merged**
